name: baker_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.21.0+1
  objectbox: ^1.4.1
  objectbox_flutter_libs: any
  # hive: ^2.0.3
  # hive_flutter: ^1.0.0
  intl: ^0.17.0
  path_provider: ^2.0.4
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any
  # flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/images/rasters/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/rasters/
    - assets/images/vectors/

  fonts:
    - family: Okta
      fonts:
        - asset: assets/fonts/Okta_Neue_Heavy.otf
          weight: 900
        - asset: assets/fonts/Okta_Neue_Black.otf
          weight: 800
        - asset: assets/fonts/Okta_Neue_Bold.otf
          weight: 700
        - asset: assets/fonts/Okta_Neue_SemiBold.otf
          weight: 600
        - asset: assets/fonts/Okta_Neue_Medium.otf
          weight: 500
        - asset: assets/fonts/Okta_Neue_Regular.otf
          weight: 400
        - asset: assets/fonts/Okta_Neue_Normal.otf
          weight: 300
        - asset: assets/fonts/Okta_Neue_UltraLight.otf
          weight: 200
        - asset: assets/fonts/Okta_Neue_Thin.otf
          weight: 100
